# coding: utf-8

"""
    API

    Audius V1 API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pyaudius.models.reply_comment import ReplyComment

class TestReplyComment(unittest.TestCase):
    """ReplyComment unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ReplyComment:
        """Test ReplyComment
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ReplyComment`
        """
        model = ReplyComment()
        if include_optional:
            return ReplyComment(
                id = '',
                user_id = '',
                message = '',
                mentions = [
                    pyaudius.models.comment_mention.comment_mention(
                        user_id = 56, 
                        handle = '', )
                    ],
                track_timestamp_s = 56,
                react_count = 56,
                is_edited = True,
                is_current_user_reacted = True,
                is_artist_reacted = True,
                created_at = '',
                updated_at = ''
            )
        else:
            return ReplyComment(
                id = '',
                user_id = '',
                message = '',
                react_count = 56,
                is_edited = True,
                created_at = '',
        )
        """

    def testReplyComment(self):
        """Test ReplyComment"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
