# coding: utf-8

"""
    API

    Audius V1 API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pyaudius.models.decoded_user_token import DecodedUserToken

class TestDecodedUserToken(unittest.TestCase):
    """DecodedUserToken unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DecodedUserToken:
        """Test DecodedUserToken
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DecodedUserToken`
        """
        model = DecodedUserToken()
        if include_optional:
            return DecodedUserToken(
                user_id = '',
                email = '',
                name = '',
                handle = '',
                verified = True,
                profile_picture = pyaudius.models.profile_picture.profilePicture(
                    150x150 = '', 
                    480x480 = '', 
                    1000x1000 = '', ),
                sub = '',
                iat = ''
            )
        else:
            return DecodedUserToken(
                user_id = '',
                email = '',
                name = '',
                handle = '',
                verified = True,
                sub = '',
                iat = '',
        )
        """

    def testDecodedUserToken(self):
        """Test DecodedUserToken"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
