# coding: utf-8

"""
    API

    Audius V1 API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pyaudius.models.user_associated_wallet_response import UserAssociatedWalletResponse

class TestUserAssociatedWalletResponse(unittest.TestCase):
    """UserAssociatedWalletResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserAssociatedWalletResponse:
        """Test UserAssociatedWalletResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserAssociatedWalletResponse`
        """
        model = UserAssociatedWalletResponse()
        if include_optional:
            return UserAssociatedWalletResponse(
                data = pyaudius.models.encoded_user_id.encoded_user_id(
                    user_id = '', )
            )
        else:
            return UserAssociatedWalletResponse(
        )
        """

    def testUserAssociatedWalletResponse(self):
        """Test UserAssociatedWalletResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
