# coding: utf-8

"""
    API

    Audius V1 API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pyaudius.models.access_info_response import AccessInfoResponse

class TestAccessInfoResponse(unittest.TestCase):
    """AccessInfoResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AccessInfoResponse:
        """Test AccessInfoResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AccessInfoResponse`
        """
        model = AccessInfoResponse()
        if include_optional:
            return AccessInfoResponse(
                data = pyaudius.models.track_access_info.track_access_info(
                    access = pyaudius.models.access.access(), 
                    user_id = '', 
                    blocknumber = 56, 
                    is_stream_gated = True, 
                    stream_conditions = pyaudius.models.stream_conditions.stream_conditions(), 
                    is_download_gated = True, 
                    download_conditions = pyaudius.models.download_conditions.download_conditions(), )
            )
        else:
            return AccessInfoResponse(
        )
        """

    def testAccessInfoResponse(self):
        """Test AccessInfoResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
