# coding: utf-8

"""
    API

    Audius V1 API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pyaudius.models.verify_token import VerifyToken

class TestVerifyToken(unittest.TestCase):
    """VerifyToken unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VerifyToken:
        """Test VerifyToken
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VerifyToken`
        """
        model = VerifyToken()
        if include_optional:
            return VerifyToken(
                data = pyaudius.models.decoded_user_token.decoded_user_token(
                    user_id = '', 
                    email = '', 
                    name = '', 
                    handle = '', 
                    verified = True, 
                    profile_picture = pyaudius.models.profile_picture.profilePicture(
                        150x150 = '', 
                        480x480 = '', 
                        1000x1000 = '', ), 
                    sub = '', 
                    iat = '', )
            )
        else:
            return VerifyToken(
        )
        """

    def testVerifyToken(self):
        """Test VerifyToken"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
