# coding: utf-8

"""
    API

    Audius V1 API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pyaudius.models.authorized_apps import AuthorizedApps

class TestAuthorizedApps(unittest.TestCase):
    """AuthorizedApps unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AuthorizedApps:
        """Test AuthorizedApps
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AuthorizedApps`
        """
        model = AuthorizedApps()
        if include_optional:
            return AuthorizedApps(
                data = [
                    pyaudius.models.authorized_app.authorized_app(
                        address = '', 
                        name = '', 
                        description = '', 
                        image_url = '', 
                        grantor_user_id = '', 
                        grant_created_at = '', 
                        grant_updated_at = '', )
                    ]
            )
        else:
            return AuthorizedApps(
        )
        """

    def testAuthorizedApps(self):
        """Test AuthorizedApps"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
