# coding: utf-8

"""
    API

    Audius V1 API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pyaudius.api.challenges_api import ChallengesApi


class TestChallengesApi(unittest.TestCase):
    """ChallengesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ChallengesApi()

    def tearDown(self) -> None:
        pass

    def test_get_undisbursed_challenges(self) -> None:
        """Test case for get_undisbursed_challenges

        """
        pass


if __name__ == '__main__':
    unittest.main()
