# coding: utf-8

"""
    API

    Audius V1 API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pyaudius.api.dashboard_wallet_users_api import DashboardWalletUsersApi


class TestDashboardWalletUsersApi(unittest.TestCase):
    """DashboardWalletUsersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DashboardWalletUsersApi()

    def tearDown(self) -> None:
        pass

    def test_bulk_get_dashboard_wallet_users(self) -> None:
        """Test case for bulk_get_dashboard_wallet_users

        """
        pass


if __name__ == '__main__':
    unittest.main()
