# coding: utf-8

"""
    API

    Audius V1 API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pyaudius.models.reposts import Reposts

class TestReposts(unittest.TestCase):
    """Reposts unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Reposts:
        """Test Reposts
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Reposts`
        """
        model = Reposts()
        if include_optional:
            return Reposts(
                data = [
                    pyaudius.models.activity.activity(
                        timestamp = '', 
                        item_type = 'track', 
                        item = pyaudius.models.item.item(), 
                        class = '', )
                    ]
            )
        else:
            return Reposts(
        )
        """

    def testReposts(self):
        """Test Reposts"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
