# coding: utf-8

"""
    API

    Audius V1 API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pyaudius.models.sales_aggregate_response import SalesAggregateResponse

class TestSalesAggregateResponse(unittest.TestCase):
    """SalesAggregateResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SalesAggregateResponse:
        """Test SalesAggregateResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SalesAggregateResponse`
        """
        model = SalesAggregateResponse()
        if include_optional:
            return SalesAggregateResponse(
                data = [
                    pyaudius.models.sales_aggregate.sales_aggregate(
                        content_type = '', 
                        content_id = '', 
                        purchase_count = 56, )
                    ]
            )
        else:
            return SalesAggregateResponse(
        )
        """

    def testSalesAggregateResponse(self):
        """Test SalesAggregateResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
