# coding: utf-8

"""
    API

    Audius V1 API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pyaudius.models.undisbursed_challenge import UndisbursedChallenge

class TestUndisbursedChallenge(unittest.TestCase):
    """UndisbursedChallenge unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UndisbursedChallenge:
        """Test UndisbursedChallenge
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UndisbursedChallenge`
        """
        model = UndisbursedChallenge()
        if include_optional:
            return UndisbursedChallenge(
                challenge_id = '',
                user_id = '',
                specifier = '',
                amount = '',
                completed_blocknumber = 56,
                handle = '',
                wallet = '',
                created_at = '',
                completed_at = '',
                cooldown_days = 56
            )
        else:
            return UndisbursedChallenge(
                challenge_id = '',
                user_id = '',
                specifier = '',
                amount = '',
                completed_blocknumber = 56,
                handle = '',
                wallet = '',
                created_at = '',
                completed_at = '',
        )
        """

    def testUndisbursedChallenge(self):
        """Test UndisbursedChallenge"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
