# coding: utf-8

"""
    API

    Audius V1 API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pyaudius.models.track_access_info import TrackAccessInfo

class TestTrackAccessInfo(unittest.TestCase):
    """TrackAccessInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TrackAccessInfo:
        """Test TrackAccessInfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TrackAccessInfo`
        """
        model = TrackAccessInfo()
        if include_optional:
            return TrackAccessInfo(
                access = pyaudius.models.access.access(
                    stream = True, 
                    download = True, ),
                user_id = '',
                blocknumber = 56,
                is_stream_gated = True,
                stream_conditions = None,
                is_download_gated = True,
                download_conditions = None
            )
        else:
            return TrackAccessInfo(
                user_id = '',
                blocknumber = 56,
        )
        """

    def testTrackAccessInfo(self):
        """Test TrackAccessInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
