# coding: utf-8

"""
    API

    Audius V1 API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pyaudius.models.user_tracks_remixed_response import UserTracksRemixedResponse

class TestUserTracksRemixedResponse(unittest.TestCase):
    """UserTracksRemixedResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserTracksRemixedResponse:
        """Test UserTracksRemixedResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserTracksRemixedResponse`
        """
        model = UserTracksRemixedResponse()
        if include_optional:
            return UserTracksRemixedResponse(
                data = [
                    pyaudius.models.remixed_track_aggregate.remixed_track_aggregate(
                        track_id = '', 
                        title = '', 
                        remix_count = 56, )
                    ]
            )
        else:
            return UserTracksRemixedResponse(
        )
        """

    def testUserTracksRemixedResponse(self):
        """Test UserTracksRemixedResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
