# coding: utf-8

"""
    API

    Audius V1 API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pyaudius.models.track_artwork import TrackArtwork

class TestTrackArtwork(unittest.TestCase):
    """TrackArtwork unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TrackArtwork:
        """Test TrackArtwork
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TrackArtwork`
        """
        model = TrackArtwork()
        if include_optional:
            return TrackArtwork(
                var_150x150 = '',
                var_480x480 = '',
                var_1000x1000 = ''
            )
        else:
            return TrackArtwork(
        )
        """

    def testTrackArtwork(self):
        """Test TrackArtwork"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
