# coding: utf-8

"""
    API

    Audius V1 API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pyaudius.models.get_challenges import GetChallenges

class TestGetChallenges(unittest.TestCase):
    """GetChallenges unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetChallenges:
        """Test GetChallenges
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetChallenges`
        """
        model = GetChallenges()
        if include_optional:
            return GetChallenges(
                data = [
                    pyaudius.models.challenge_response.challenge_response(
                        challenge_id = '', 
                        user_id = '', 
                        specifier = '', 
                        is_complete = True, 
                        is_active = True, 
                        is_disbursed = True, 
                        current_step_count = 56, 
                        max_steps = 56, 
                        challenge_type = '', 
                        amount = '', 
                        disbursed_amount = 56, 
                        cooldown_days = 56, 
                        metadata = pyaudius.models.metadata.metadata(), )
                    ]
            )
        else:
            return GetChallenges(
        )
        """

    def testGetChallenges(self):
        """Test GetChallenges"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
