# coding: utf-8

"""
    API

    Audius V1 API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pyaudius.models.track_comments_response import TrackCommentsResponse

class TestTrackCommentsResponse(unittest.TestCase):
    """TrackCommentsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TrackCommentsResponse:
        """Test TrackCommentsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TrackCommentsResponse`
        """
        model = TrackCommentsResponse()
        if include_optional:
            return TrackCommentsResponse(
                data = [
                    pyaudius.models.comment.comment(
                        id = '', 
                        user_id = '', 
                        message = '', 
                        mentions = [
                            pyaudius.models.comment_mention.comment_mention(
                                user_id = 56, 
                                handle = '', )
                            ], 
                        track_timestamp_s = 56, 
                        react_count = 56, 
                        reply_count = 56, 
                        is_edited = True, 
                        is_current_user_reacted = True, 
                        is_artist_reacted = True, 
                        is_tombstone = True, 
                        is_muted = True, 
                        created_at = '', 
                        updated_at = '', 
                        replies = [
                            pyaudius.models.reply_comment.reply_comment(
                                id = '', 
                                user_id = '', 
                                message = '', 
                                track_timestamp_s = 56, 
                                react_count = 56, 
                                is_edited = True, 
                                is_current_user_reacted = True, 
                                is_artist_reacted = True, 
                                created_at = '', 
                                updated_at = '', )
                            ], )
                    ]
            )
        else:
            return TrackCommentsResponse(
        )
        """

    def testTrackCommentsResponse(self):
        """Test TrackCommentsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
