# coding: utf-8

"""
    API

    Audius V1 API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pyaudius.models.track_comment_notification_response import TrackCommentNotificationResponse

class TestTrackCommentNotificationResponse(unittest.TestCase):
    """TrackCommentNotificationResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TrackCommentNotificationResponse:
        """Test TrackCommentNotificationResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TrackCommentNotificationResponse`
        """
        model = TrackCommentNotificationResponse()
        if include_optional:
            return TrackCommentNotificationResponse(
                data = pyaudius.models.comment_notification_setting.comment_notification_setting(
                    is_muted = True, )
            )
        else:
            return TrackCommentNotificationResponse(
        )
        """

    def testTrackCommentNotificationResponse(self):
        """Test TrackCommentNotificationResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
