# coding: utf-8

"""
    API

    Audius V1 API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pyaudius.api.tips_api import TipsApi


class TestTipsApi(unittest.TestCase):
    """TipsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TipsApi()

    def tearDown(self) -> None:
        pass

    def test_get_tips(self) -> None:
        """Test case for get_tips

        """
        pass


if __name__ == '__main__':
    unittest.main()
