# coding: utf-8

"""
    API

    Audius V1 API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pyaudius.models.developer_apps import DeveloperApps

class TestDeveloperApps(unittest.TestCase):
    """DeveloperApps unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeveloperApps:
        """Test DeveloperApps
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DeveloperApps`
        """
        model = DeveloperApps()
        if include_optional:
            return DeveloperApps(
                data = [
                    pyaudius.models.developer_app.developer_app(
                        address = '', 
                        user_id = '', 
                        name = '', 
                        description = '', 
                        image_url = '', )
                    ]
            )
        else:
            return DeveloperApps(
        )
        """

    def testDeveloperApps(self):
        """Test DeveloperApps"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
