# coding: utf-8

"""
    API

    Audius V1 API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pyaudius.models.nft_collection import NftCollection

class TestNftCollection(unittest.TestCase):
    """NftCollection unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NftCollection:
        """Test NftCollection
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NftCollection`
        """
        model = NftCollection()
        if include_optional:
            return NftCollection(
                chain = 'eth',
                standard = 'ERC721',
                address = '',
                name = '',
                image_url = '',
                external_link = ''
            )
        else:
            return NftCollection(
                chain = 'eth',
                address = '',
                name = '',
        )
        """

    def testNftCollection(self):
        """Test NftCollection"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
