# coding: utf-8

"""
    API

    Audius V1 API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pyaudius.api.resolve_api import ResolveApi


class TestResolveApi(unittest.TestCase):
    """ResolveApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ResolveApi()

    def tearDown(self) -> None:
        pass

    def test_resolve(self) -> None:
        """Test case for resolve

        Resolves and redirects a provided Audius app URL to the API resource URL it represents
        """
        pass


if __name__ == '__main__':
    unittest.main()
