# coding: utf-8

"""
    API

    Audius V1 API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pyaudius.api.comments_api import CommentsApi


class TestCommentsApi(unittest.TestCase):
    """CommentsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CommentsApi()

    def tearDown(self) -> None:
        pass

    def test_get_comment_replies(self) -> None:
        """Test case for get_comment_replies

        """
        pass

    def test_get_unclaimed_comment_id(self) -> None:
        """Test case for get_unclaimed_comment_id

        """
        pass


if __name__ == '__main__':
    unittest.main()
