# coding: utf-8

"""
    API

    Audius V1 API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pyaudius.api.developer_apps_api import DeveloperAppsApi


class TestDeveloperAppsApi(unittest.TestCase):
    """DeveloperAppsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DeveloperAppsApi()

    def tearDown(self) -> None:
        pass

    def test_get_developer_app(self) -> None:
        """Test case for get_developer_app

        """
        pass


if __name__ == '__main__':
    unittest.main()
